on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Compile prost
    steps:
      - name: Install protoc
        id: install-protoc
        uses: adamchalmers/gh-action-hw@v2
        with:
          protoc-version: 3.20
          os-arch: x86_64
          os-plat: linux
      - name: Use protoc
        run: echo "Installed ${{ steps.install-protoc.outputs.version }} at ${{ steps.install-protoc.outputs.path }}"
